# Generated by Django 4.0.4 on 2022-06-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_category_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='None', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
